---
- name: Link bash configuration directory
  ansible.builtin.file:
    src: '{{ role_path }}/bash'
    dest: '{{ ansible_env.HOME }}/.config/bash'
    state: link

- name: Link inputrc configuration
  ansible.builtin.file:
    src: '{{ role_path }}/inputrc'
    dest: '{{ ansible_env.HOME }}/.inputrc'
    state: link

- name: Link bashrc to bash init
  ansible.builtin.file:
    src: '{{ ansible_env.HOME }}/.config/bash/init.bash'
    dest: '{{ ansible_env.HOME }}/.bashrc'
    state: link

- name: Remove bash profile to force it to load profile
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.bash_profile'
    state: absent

