#!/usr/bin/env bash
#
# https://github.com/sandorex/config
# wrapper to call ansible-playbook from the virtualenv

cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1

# activate the virtualenv
source ./scripts/activate

ansible-playbook "$@"

