- name: Gaming container bootstrap
  hosts: localhost
  connection: local
  vars:
    proton_ge_versions:
      - GE-Proton8-30
      - GE-Proton8-29
    pacman_packages:
      - vulkan-radeon
      - lib32-vulkan-radeon
        #- amdvlk # i do not know if this is needed
      - ttf-liberation # used by steam to replace ariel font
      - gamemode # might slightly boost performance
      - steam

      # core utils
      - perl
      - coreutils

      # editor so i dont have to use vim
      - nano

      # for terminal usage
      - kitty-terminfo
  tasks:
    - name: Fail if ran outside of a container
      ansible.builtin.fail:
        msg: This playbook should only be ran inside a container
      when: ansible_env.container is not defined

    - name: Uncomment en_US.UTF-8 locale
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/locale.gen
        regexp: '^#en_US.UTF-8 UTF-8'
        line: 'en_US.UTF-8 UTF-8'
      register: commentline

    - name: Regenerate locale
      become: yes
      ansible.builtin.command:
        cmd: locale-gen
      when: commentline.changed

    - name: Enable multilib
      become: yes
      ansible.builtin.blockinfile:
        path: /etc/pacman.conf
        insertafter: EOF
        marker: "## {mark} managed by ansible (enable multilib)"
        block: |
          [multilib]
          Include = /etc/pacman.d/mirrorlist
      register: multilib_enable

    - name: Update packages
      become: yes
      ansible.builtin.command:
        cmd: pacman -Syuu --noconfirm
      when: multilib_enable.changed

    - name: Installing extra packages # TODO use the pacman community module for this
      become: yes
      ansible.builtin.command:
        cmd: 'pacman -S --noconfirm {{ pacman_packages | join(" ") }}'

    - name: Download proton-ge versions
      tags:
        - proton
        - update
      with_items: '{{ proton_ge_versions }}'
      ansible.builtin.include_tasks:
        file: '{{ playbook_dir }}/extras/install-proton-ge.yml'
        apply:
          vars:
            release: '{{ item }}'

    # TODO do this only once somehow
    - name: Export Steam to host
      ansible.builtin.command:
        cmd: distrobox-export --app 'Steam'

