#!/usr/bin/env bash
#
# https://github.com/sandorex/config
# automatically copies dotfiles to remote host and opens a shell, made to simplify running
# playbooks on remote machines

shopt -s extglob

DIR=$(realpath "$(dirname "${BASH_SOURCE[0]}")")

cd "$DIR" | exit 99

# TODO automate ssh key exchange, maybe include a known public ssh key
if [[ -z "$1" ]]; then
    cat <<EOF
Usage: $0 <user@host>

You will be asked for a password twice if SSH key authentication is not setup

EOF
    exit 1
fi

ip="$1"
shift

rm -f archive.tar

# archive repository everything but the tar itself and venv
tar -cf archive.tar --exclude='venv/*' \
                    --exclude='*.tar' \
                    ./* ./.*

echo "$(tput bold):: Transfering dotfiles from $(uname -n) to target ($ip)$(tput sgr0)"

# the host is unknown and i just dont want to deal with this
SSH_FLAGS=(-q -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null")

# transfer archive to home of user
scp "${SSH_FLAGS[@]}" archive.tar scp://"$ip"/

rm -f archive.tar

ssh "${SSH_FLAGS[@]}" "$ip" -t 'mkdir -p .dotfiles \
    && tar -C .dotfiles -xf archive.tar \
    && rm -f archive.tar \
    && cd .dotfiles \
    && printf "\n%s\n%s\n%s\n%s\n\n%s\n\n" "$(tput bold)Options:" "- For automated setup use ./auto-setup" "- For manual use, use ./ansible-playbook" "- Or use ansible directly by sourcing ./scripts/activate$(tput sgr0)" "If you wish to reset git to last commit run git reset --hard HEAD" \
    && $SHELL -i'

