LABEL name="arcam-fedora-nix" \
      summary="fedora-toolbox based image for arcam with nix package manager" \
      maintainer="Sandorex <rzhw3h@gmail.com>"

ARG SHA=latest
FROM arcam-fedora-base:$SHA

# install nix
RUN sh <(curl -L https://nixos.org/nix/install) --daemon

# nix should be started early so scripts can use it
COPY ./init.d/nix.sh /init.d/05-nix.sh

# copy config
COPY ./fedora-nix/config.toml /config.toml

COPY ./help.sh /help.sh
ENTRYPOINT [ "/help.sh" ]
