#!/usr/bin/env just --justfile

_default:
    @{{ just_executable() }} -f {{ justfile() }} --list

# build all images
build-all:
    {{ justfile_directory() }}/fedora/fedora.sh --all

# publish all images
publish-all:
   {{ justfile_directory() }}/fedora/fedora.sh --publish --all
