---
- name: Link bash configuration directory
  ansible.builtin.file:
    src: '{{ role_path }}/files/.config/bash'
    dest: '{{ ansible_env.HOME }}/.config/bash'
    state: link
    force: true

- name: Link inputrc configuration
  ansible.builtin.file:
    src: '{{ role_path }}/files/.inputrc'
    dest: '{{ ansible_env.HOME }}/.inputrc'
    state: link
    force: true

- name: Link bashrc
  ansible.builtin.file:
    src: '{{ role_path }}/files/.bashrc'
    dest: '{{ ansible_env.HOME }}/.bashrc'
    state: link
    force: true

-  name: Link bash_profile
   ansible.builtin.file:
    src: '{{ role_path }}/files/.bash_profile'
    dest: '{{ ansible_env.HOME }}/.bash_profile'
    state: link
    force: true
