---
- name: Link bash configuration directory
  ansible.builtin.file:
    src: '{{ role_path }}/files/.config/bash'
    dest: '{{ ansible_env.HOME }}/.config/bash'
    state: link
    force: true

- name: Link inputrc configuration
  ansible.builtin.file:
    src: '{{ role_path }}/files/.inputrc'
    dest: '{{ ansible_env.HOME }}/.inputrc'
    state: link
    force: true

- name: Link bashrc to bash init
  ansible.builtin.file:
    src: '{{ ansible_env.HOME }}/.config/bash/init.bash'
    dest: '{{ ansible_env.HOME }}/.bashrc'
    state: link
    force: true

- name: Create bash_profile to load profile and bashrc
  ansible.builtin.copy:
    content: |
      # source the actual profile and bashrc (includes check for interactive shell)
      source ~/.profile
      source ~/.bashrc
    dest: '{{ ansible_env.HOME }}/.bash_profile'

