---
- name: Link git configuration file
  ansible.builtin.file:
    src: '{{ role_path }}/files/.gitconfig'
    dest: '{{ ansible_env.HOME }}/.gitconfig'
    state: link
    force: true

- name: Link git template directory
  ansible.builtin.file:
    src: '{{ role_path }}/files/.git-template'
    dest: '{{ ansible_env.HOME }}/.git-template'
    state: link
    force: true

