---
- block:
    - name: Ensure ~/.local/bin exists
      ansible.builtin.file:
        path: '{{ ansible_env.HOME }}/.local/bin'
        state: directory

    # TODO switch to the archived one as appimage requires libfuse
    - name: Download neovim
      vars:
        neovim_release: '{{ neovim_version }}'
        neovim_checksum: '{{ neovim_checksum }}'
      ansible.builtin.get_url:
        url: 'https://github.com/neovim/neovim/releases/download/{{ neovim_release }}/nvim.appimage'
        checksum: 'sha256:{{ neovim_checksum }}'
        dest: '{{ ansible_env.HOME }}/.local/bin/nvim'
        mode: u+rwx # make sure its executable
  when: "'neovim' in install"

- name: Link neovim configuration directory
  ansible.builtin.file:
    src: '{{ role_path }}/files/.config/nvim'
    dest: '{{ ansible_env.HOME }}/.config/nvim'
    state: link
    force: true
  when: "'neovim' in configure"

# TODO redo this when nvim wrapper is tested
# TODO ensure flatpak directory exists
# - name: Link neovim configuration directory (flatpak)
#   ansible.builtin.file:
#     src: '{{ role_path }}/files/.config/nvim'
#     dest: '{{ ansible_env.HOME }}/.var/app/io.neovim.nvim/config/nvim'
#     state: link
#   when: neovim_flatpak
