---
- name: Ensure directory exists
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
  loop:
    - '{{ ansible_env.HOME }}/.local/share/qalculate'
    - '{{ ansible_env.HOME }}/.var/app/io.github.Qalculate.qalculate-qt/data/qalculate'

- name: Link qalculate config (native)
  ansible.builtin.file:
    src: '{{ role_path }}/files/.local/share/qalculate/definitions'
    dest: '{{ ansible_env.HOME }}/.local/share/qalculate/definitions'
    state: link
    force: true

- name: Link qalculate config (flatpak)
  ansible.builtin.file:
    src: '{{ ansible_env.HOME }}/.local/share/qalculate/definitions'
    dest: '{{ ansible_env.HOME }}/.var/app/io.github.Qalculate.qalculate-qt/data/qalculate/definitions'
    state: link
    force: true
  register: link

- name: Allow qalculate flatpak to share native config
  ansible.builtin.command:
    cmd: 'flatpak override io.github.Qalculate.qalculate-qt --filesystem="{{ role_path }}/files/.local/share/qalculate"'
  # it will fail if installed in flatpak systemwide
  ignore_errors: true
  when: link.changed

