---
- name: Ensure directory ~/.ssh exists
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.ssh'
    state: directory
    mode: 0700

- name: Copy ssh configuration file
  ansible.builtin.copy:
    src: '{{ role_path }}/files/.ssh/config'
    dest: '{{ ansible_env.HOME }}/.ssh/config'
    mode: 0600

- name: Create connnections ssh directory
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.ssh/connections'
    state: directory
    mode: 0700

- name: Generate new ssh keys
  loop:
    - '@github.com'
    - '@gitlab.com'
  ansible.builtin.command:
    cmd: ssh-keygen -N '' -t ed25519 -f '{{ ansible_env.HOME }}/.ssh/{{ item }}'
    creates: '{{ ansible_env.HOME }}/.ssh/{{ item }}'
