#!/bin/sh
#
# .profile - place to put env vars
#
# THIS SHOULD NOT RUN ON START OF EACH SHELL
# SYMLINK .zprofile TO THIS FILE

export DOTFILES="$HOME/.dotfiles"       # dotfiles path
export AGSHELLDIR="$HOME/.config/shell" # agnostic shell stuff
export RUSTUP_HOME="$HOME/.rustup"
export GOPATH="$HOME/.golang"           # GOPATH defaults to $HOME/go ugh
export NPM_HOME="$HOME/.npm-packages"   # npm global user install

PATH="$PATH:$HOME/.bin"
PATH="$PATH:$HOME/.local/bin"
PATH="$PATH:$HOME/.cargo/bin"
PATH="$PATH:$GOPATH/bin"
PATH="$PATH:$NPM_HOME/bin"
PATH="$PATH:$HOME/.local/share/bob/nvim-bin"
PATH="$PATH:$HOME/.bin/polyfill"        # fallback path for optional software

if command -v fnm >/dev/null && [ -z "$FNM_DIR" ]; then
    eval "$(fnm env)"
fi

export PATH

# nano is default, override in shell
export EDITOR=nano
export SUDO_EDITOR=nano
export TASK_EDITOR=nano

# options for less
# FRX is git default args
export LESS='FRX --mouse'

export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# set ls colors
eval "$(dircolors --sh "$AGSHELLDIR/gruvbox.dircolors")"

# to signify if its running twice
[[ -n "$__PROFILE_RAN" ]] && echo "~/.profile is being ran twice, stop it, get some help"
export __PROFILE_RAN=1

