---
- tags: mouse
  ansible.builtin.import_tasks:
    file: '{{ role_path }}/tasks/mouse.yml'

- tags: wacom
  ansible.builtin.import_tasks:
    file: '{{ role_path }}/tasks/wacom.yml'

- tags: keyboard
  ansible.builtin.import_tasks:
    file: '{{ role_path }}/tasks/keyboard.yml'

- tags: theming
  ansible.builtin.import_tasks:
    file: '{{ role_path }}/tasks/theming.yml'

- ansible.builtin.import_tasks:
    file: '{{ role_path }}/tasks/other.yml'

