---
# TODO user is not in sudo by default on debian, figure out a way to automate this without
# requiring same password for root and user
# for now run: su - root adduser <user> sudo
# - name: Add user to sudoers
#   ansible.builtin.user:
#     name: '{{ ansible_user_id }}'
#     append: true
#     groups:
#       - sudo
#   become: yes
#   become_method: su
#   become_flags: '-s /bin/bash -c'

- become: yes
  tags: [never, root]
  block:
    - name: Add apt repository (main)
      ansible.builtin.apt_repository:
        repo: 'deb http://deb.debian.org/debian {{ ansible_distribution_release }} main contrib non-free non-free-firmware'
        state: present
      notify: 'Update APT Cache'

    - name: Add apt repository (updates)
      ansible.builtin.apt_repository:
        repo: 'deb http://deb.debian.org/debian {{ ansible_distribution_release }}-updates main contrib non-free non-free-firmware'
        state: present
      notify: 'Update APT Cache'

    - name: Add apt repository (backports)
      ansible.builtin.apt_repository:
        repo: 'deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main contrib non-free non-free-firmware'
        state: present
      notify: 'Update APT Cache'

    - name: Add apt repository (security)
      ansible.builtin.apt_repository:
        repo: 'deb http://deb.debian.org/debian-security {{ ansible_distribution_release }}-security main contrib non-free non-free-firmware'
        state: present
      notify: 'Update APT Cache'

    # the original sources.list is preserved and the new sources are in sources.list.d and managed by ansible
    - name: Remove default sources.list
      ansible.builtin.file:
        path: /etc/apt/sources.list
        state: absent
      notify: 'Update APT Cache'

    - name: Configure apt automation
      ansible.builtin.copy:
        content: |
          // updates the package cache every day
          APT::Periodic::Update-Package-Lists "1";

          // pre-download the updates every day
          APT::Periodic::Download-Upgradeable-Packages "1";

          // automatic cleaning every 3 days
          APT::Periodic::AutocleanInterval "3";

        dest: /etc/apt/apt.conf.d/10-periodic-update-cache
        mode: 0644
        owner: root
