---
# TODO i do not know where non-flatpak app stores things, also link to qalc cli frontend
- name: Link qalculate config
  ansible.builtin.file:
    src: '{{ role_path }}/files/definitions'
    dest: '{{ ansible_env.HOME }}/.var/app/io.github.Qalculate.qalculate-qt/data/qalculate/definitions'
    state: link
  register: link

# as its a flatpak it is sandboxed
# NOTE: this wont work with system flatpak as it requires root permissions
- name: Allow flatpak access to config
  ansible.builtin.command:
    cmd: 'flatpak override io.github.Qalculate.qalculate-qt --filesystem="{{ role_path }}/files/"'
  when: link.changed

