---
# thorium desktop

neovim_install: true

kde_mouse_settings:
  - name: 'E-Signal USB Gaming Mouse'
    pid: '1241'
    vid: '41119'
    accel: ' -0.200'
    accelProfile: 1
  - name: 'Logitech Wireless Mouse PID:4022'
    pid: '1133'
    vid: '16418'
    accel: '0.200'
    accelProfile: 1

kde_wacom_settings:
  - name: 'Wacom One by Wacom S Pen'
    pid: '1386'
    vid: '890'
    leftHanded: false
    outputArea: '0,0,1,1'

kde_default_terminal: kitty
kde_default_browser: vivaldi-stable

