---
- name: Install ranger file manager using pipx
  community.general.pipx:
    executable: 'pipx'
    name: ranger-fm
    state: present
  when: ranger_install

- name: Link ranger configuration directory
  ansible.builtin.file:
    src: '{{ role_path }}/ranger'
    dest: '{{ ansible_env.HOME }}/.config/ranger'
    state: link

