---
- name: Ensure proper permissions on ~/.ssh
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.ssh'
    state: touch
    mode: 0700

- name: Copy ssh configuration file
  ansible.builtin.copy:
    src: '{{ role_path }}/config'
    dest: '{{ ansible_env.HOME }}/.ssh/config'
    mode: 0600

