---
# install flatpak for multiple distros

- name: Install flatpak
  ansible.builtin.package:
    name: flatpak
    state: present

# - name: Install flatpak (APT)
#   ansible.builtin.apt:
#     name: flatpak
#     state: present
#   when: ansible_env.ansible_pkg_mgr == 'apt'
#
# - name: Install flatpak (pacman)
#   ansible.builtin.pacman:
#     name: flatpak
#     state: present
#   when: ansible_env.ansible_pkg_mgr == 'pacman'


