---
# NOTE: this should work on most package managers right?
- name: Install flatpak
  ansible.builtin.package:
    name: flatpak
    state: present
  become: yes
  tags: [never, root]

- name: Add the flathub repository (user)
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

# - name: Add the flathub repository (system)
#   community.general.flatpak_remote:
#     name: flathub-system
#     state: present
#     flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
#     method: system
#   become: yes

- name: Install flatpak apps
  community.general.flatpak:
    name: '{{ flatpak_install }}'
    method: user
    state: present
  when: flatpak_install is defined

