---
- name: Link ZSH config directory
  ansible.builtin.file:
    src: '{{ role_path }}/zsh'
    dest: '{{ ansible_env.HOME }}/.config/zsh'
    state: link

- name: Link ZSH init file
  ansible.builtin.file:
    src: '{{ ansible_env.HOME }}/.config/zsh/init.zsh'
    dest: '{{ ansible_env.HOME }}/.zshrc'
    state: link

- name: Link zprofile to profile
  ansible.builtin.file:
    src: '{{ ansible_env.HOME }}/.profile'
    dest: '{{ ansible_env.HOME }}/.zprofile'
    state: link

- name: Delete zsh files to force it to load zprofile
  loop:
    - '.zshenv'
    - '.zlogin'
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/{{ item }}'
    state: absent

