---
# TODO Figure out a way to keep it linked while ignoring [user] section
# - name: Link git configuration file
#   ansible.builtin.file:
#     src: '{{ role_path }}/gitconfig'
#     dest: '{{ ansible_env.HOME }}/.gitconfig'
#     state: link

- name: Template git configuration file
  vars:
    git_email: 'rzhw3h@gmail.com'
    git_username: 'sandorex'
  ansible.builtin.template:
    src: '{{ role_path }}/gitconfig'
    dest: '{{ ansible_env.HOME }}/.gitconfig'

- name: Link git template directory
  ansible.builtin.file:
    src: '{{ role_path }}/template'
    dest: '{{ ansible_env.HOME }}/.git-template'
    state: link

