version = 1

[[config]]
name = "dev-fedora"
image = "ghcr.io/sandorex/dev-fedora"
network = true

[config.podman]
engine_args = [
    "--volume", "box-data:/data"
]
env = { "NVIM_FORCE_OSC52" = "true" }
