version = 1

[[config]]
name = "dev-fedora"
image = "ghcr.io/sandorex/dev-fedora"
network = true

[config.podman]
engine_args = [
    # mainly used by neovim
    "--volume=box-data:/data",

    # cache nix packages
    "--volume=nix:/nix"
]
env = { "NVIM_FORCE_OSC52" = "true" }
