#!/usr/bin/env bash
# generate debug keystore for non store apk builds

keytool -genkey \
        -v \
        -keystore debug.keystore \
        -storepass android \
        -alias androiddebugkey \
        -keypass android \
        -keyalg RSA \
        -keysize 2048 \
        -validity 10000
