#!/usr/bin/env bash
#
# https://github.com/sandorex/config
# monb
# tool to set monitor brightness, used in terminal and using slider execute
# applet in kde plasma, has monitor brightness offset which is very important

# these offsets are added to brightness value when a literal value is set, it
# is used to make monitors the same apparent brightness as they usually are not
# equal out of the box if they are different models
monitor_offset=( '0' '-20' ) # 0  -20

# adding padding to make the array start with index 1
monitor_offset=( 'padding' "${monitor_offset[@]}" )

list_monitors() { ddcutil detect | awk ' /^Display [0-9]+/ { printf $2 " " }'; }

send() {
    local display=${1:?}
    local brightness="${2:?}"

    # easiest way to prevent sending invalid numbers
    if [[ "$brightness" -lt 0 ]]; then
        brightness='0'
    elif [[ "$brightness" -gt 100 ]]; then
        brightness='100'
    fi

    echo "Display $display ${brightness}%"
    ddcutil --display "$display" setvcp 10 "$brightness"
}

MONITOR=$2

case "$1" in
    # set literal value
    [0-9]|[1-9][0-9]|100)
        if [[ -n "$MONITOR" ]]; then
            send "$MONITOR" "$1"
        else
            for d in $(list_monitors); do
                # use the offset to make the monitors seem the same brightness
                offset="${monitor_offset[$d]}"
                if [[ -n "$offset" ]]; then
                    send "$d" "$(( $1 + offset ))"
                else
                    send "$d" "$1"
                fi
            done
        fi
        ;;
    # set relative value +10 / -10
    [+-][1-9]|[+-][1-9][0-9])
        # this is pretty unreadable but its pretty much to reduce amount of code
        if [[ -n "$MONITOR" ]]; then
            send "$MONITOR" "${1:0:1}" "${1:1}"
        else
            for d in $(list_monitors); do
                send "$d" "${1:0:1}" "${1:1}"
            done
        fi
        ;;
    l|list)
        ddcutil detect
        ;;
    ## PRESETS ##
    day)
        "$0" 30
        ;;
    night)
        "$0" 15
        ;;
    *)
        echo "Getting display brightness"

        # print brightness for each display
        for d in $(list_monitors); do
            echo -n "$d: "
            ddcutil --display "$d" getvcp 10
        done
        ;;
esac

