#!/usr/bin/env bash
# toggles dark mode in kde plasma by switching a colorscheme

set -e

COLOR_DARK="BreezeDark"
COLOR_LIGHT="BreezeClassic"

function notify() {
    notify-send -a toggle-dark-theme-kde -i color-picker 'Color Scheme Changed' "$*" || true
}

current="$(plasma-apply-colorscheme -l | grep 'current color scheme')"
case "$current" in
    *"$COLOR_DARK"*)
        plasma-apply-colorscheme "$COLOR_LIGHT"
        notify "Colorscheme set to $COLOR_LIGHT"
        ;;
    *)
        plasma-apply-colorscheme "$COLOR_DARK"
        notify "Colorscheme set to $COLOR_DARK"
        ;;
esac
