#!/usr/bin/env bash
#
# toggles the second monitor off / on

POSITIONAL_ARGS=()

while [ $# -gt 0 ]; do
    case $1 in
        --output)
            OUTPUT="$2"
            shift 2
            ;;
        -*)
            echo "Unknown option $1"
            exit 1
            ;;
        *)
            # save positional arg
            POSITIONAL_ARGS+=("$1")
            shift
            ;;
    esac
done

# restore positional parameters
set -- "${POSITIONAL_ARGS[@]}"

if [[ -z "$OUTPUT" ]]; then
    echo "Please pass output like so '$0 --output DVI-D-1'"
    exit 1
fi

if [[ "$XDG_SESSION_DESKTOP" != "KDE" ]]; then
    echo "This script works only on KDE plasma, for now.."
    exit 99
fi

function kde() {
    if [[ "$1" == 1 ]]; then
        if ! kde state; then
            kscreen-doctor output."$OUTPUT".enable
        fi
    elif [[ "$1" == 0 ]]; then
        if kde state; then
            kscreen-doctor output."$OUTPUT".disable
        fi
    elif [[ "$1" == 'state' ]]; then
        # get the state by parsing json
        state="$(kscreen-doctor -j | jq ".outputs[] | select(.name==\"$OUTPUT\").enabled")"
        if [[ "$state" == "true" ]]; then
            return 0
        elif [[ "$state" == "false" ]]; then
            return 1
        else
            # prevent confusion just fail loudly
            echo "Invalid monitor state, probably invalid output name"
            exit 1
        fi
    elif [[ -z "$1" ]]; then
        if ! kde state; then
            kde 1
        else
            kde 0
        fi
    fi
}

case "$1" in
    on|true|1)
        kde 0
        ;;
    off|false|0)
        kde 1
        ;;
    t|toggle|'')
        kde
        ;;
    *)
        echo unknown option
        exit 1
        ;;
esac

