#!/usr/bin/env bash

yt-dlp --sleep-interval 3 \
       --max-sleep-interval 15 \
       --embed-thumbnail \
       -f bestaudio \
       -x \
       --audio-format mp3 \
       --audio-quality 5 \
       --download-archive ytdlp-archive.txt \
       --yes-playlist \
       --sponsorblock-remove default \
       --exec 'rsgain custom' \
       "$@"
