LABEL name="box-fedora" \
      summary="fedora-toolbox based development container" \
      maintainer="Sandorex <rzhw3h@gmail.com>"

ARG VERSION=40
FROM registry.fedoraproject.org/fedora-toolbox:$VERSION
ARG VERSION

ENV LC_ALL=en_US.UTF-8

# improve DNF experience
RUN echo "max_parallel_downloads=10" >> /etc/dnf/dnf.conf \
    && echo "defaultyes=True" >> /etc/dnf/dnf.conf \
    && echo "fastestmirror=True" >> /etc/dnf/dnf.conf \
    && echo "install_weak_deps=False" >> /etc/dnf/dnf.conf

# install rpmfusion
RUN dnf -y install "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-${VERSION}.noarch.rpm" \
   && dnf -y install "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-${VERSION}.noarch.rpm"

# SYSTEM
COPY ./images/box-fedora/extra-packages /
RUN dnf -y install $(<extra-packages) \
    && rm /extra-packages \
    && dnf clean all

# NPM
COPY ./images/box-fedora/npm-packages /
RUN npm install -g $(<npm-packages) \
    && rm /npm-packages \
    && npm cache clean --force

# PIP
COPY ./images/box-fedora/pip-packages /
RUN pip install $(<pip-packages) \
    && rm /pip-packages \
    && pip cache purge

ENV CARGO_HOME=/usr/local/

RUN curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

# zellij takes forever to compile
RUN cargo binstall --no-confirm zellij
RUN cargo install --git https://github.com/sandorex/box

ENV CARGO_HOME=

# copy box config
COPY ./images/box-fedora/config.toml /config.toml

# copy init scripts
COPY ./init.d /init.d

# copy dotfiles if provided during build
RUN if [[ -d /dotfiles ]]; then \
        echo 'found dotfiles'; \
        rm -rf /etc/skel; \
        cp -r /dotfiles/ /etc/skel; \
    fi; true

# disable zsh newuser prompt thingy
RUN echo "zsh-newuser-install () {}" > /etc/zshenv

COPY ./help.sh /help.sh
ENTRYPOINT [ "/help.sh" ]
