#!/usr/bin/env bash
#
# https://github.com/sandorex/config

DEFAULT_HOME_PREFIX="$HOME/.dbx"

POSITIONAL_ARGS=()

while [ $# -gt 0 ]; do
    case $1 in
        --home)
            CUSTOM_HOME=$1
            shift 2
            ;;
        --home-prefix)
            export DBX_CONTAINER_HOME_PREFIX="$DEFAULT_HOME_PREFIX"
            shift
        -*)
            echo "Unknown option $1"
            exit 1
            ;;
        *)
            # save positional arg
            POSITIONAL_ARGS+=("$1")
            shift
            ;;
    esac
done

# restore positional parameters
set -- "${POSITIONAL_ARGS[@]}"

