---
# debian 12 bookworm

- name: bismuth
  hosts: localhost
  connection: local
  vars:
    kde_default_terminal: kitty

    configure:
      - bin
      - profile
      - shell

      - bash
      - zsh
      - git
      - ssh
      - neovim
      - nano
      - glow
      - yt-dlp
      - zellij
      - qalculate
      - kitty

    install:
      - neovim

    flatpak_install:
      - com.brave.Browser
      - io.github.Qalculate.qalculate-qt
      - com.stremio.Stremio
      - com.github.tchx84.Flatseal

  roles:
    - role: extras

    - role: linux
      tags: [linux, distro]

    - role: nerd-fonts
      tags: [nerd-fonts]

    - role: kde-plasma
      tags: [kde-plasma, kde, desktop]

    - role: tweaks
      tags: [distro, tweaks, fixes]

    - role: dotfiles
      tags: [dotfiles]

    - role: flatpak
      tags: [flatpak, apps]

