---
# debian 12 bookworm

- name: bismuth
  hosts: localhost
  connection: local
  vars:
    kde_default_terminal: kitty

    configure:
      - bin
      - profile
      - shell

      - bash
      - zsh
      - git
      - ssh
      - neovim
      - nano
      - glow
      - yt-dlp
      - zellij
      - qalculate
      - kitty

    install:
      - neovim

    flatpak_install:
      - com.brave.Browser
      - io.github.Qalculate.qalculate-qt
      - com.stremio.Stremio
      - com.github.tchx84.Flatseal

  pre_tasks:
    - name: Check if running on correct machine
      ansible.builtin.pause:
        prompt: 'This machine does not appear to be {{ ansible_play_name }}, if you want to continue type "yes" and press enter'
      when: ansible_nodename | lower != ansible_play_name or ansible_env.container is defined
      tags: always
      register: answer
      failed_when: answer.user_input | lower != 'yes'

    - name: Ensure ~/.config directory exists
      ansible.builtin.file:
        path: '{{ ansible_env.HOME }}/.config'
        state: directory
      tags: always

    - name: Load defaults
      ansible.builtin.include_vars:
        file: '{{ playbook_dir }}/../default.yml'
      tags: always
  roles:
    - role: linux
      tags: [linux, distro]

    - role: nerd-fonts
      tags: [nerd-fonts]

    - role: kde-plasma
      tags: [kde-plasma, kde, desktop]

    - role: tweaks
      tags: [distro, tweaks, fixes]

    - role: dotfiles
      tags: [dotfiles]

    - role: flatpak
      tags: [flatpak, apps]

