---
# debian 12 bookworm

- name: bismuth
  hosts: localhost
  connection: local
  pre_tasks:
    - name: Check if running on correct machine
      ansible.builtin.pause:
        prompt: 'This machine does not appear to be {{ ansible_play_name }}, if you want to continue type "yes" and press enter'
      when: ansible_nodename | lower != ansible_play_name or ansible_env.container is defined
      tags: always
      register: answer
      failed_when: answer.user_input | lower != 'yes'

    - name: Ensure ~/.config directory exists
      ansible.builtin.file:
        path: '{{ ansible_env.HOME }}/.config'
        state: directory
      tags: always

    - name: Load defaults
      ansible.builtin.include_vars:
        file: '{{ playbook_dir }}/../vars/default.yml'
      tags: always

    - name: Load vars
      ansible.builtin.include_vars:
        file: '{{ playbook_dir }}/../vars/{{ ansible_play_name }}.yml'
      tags: always
  roles:
    ## system ##
    - role: debian
      tags:
        - debian
        - distro

    - role: kde-plasma
      tags:
        - kde-plasma
        - kde
        - desktop

    - role: fixes
      tags:
        - distro
        - fixes

    ## terminal ##
    - role: git
      tags:
        - git
        - terminal

    - role: ssh
      tags:
        - ssh
        - terminal

    - role: zsh
      tags:
        - zsh
        - terminal

    - role: bash
      tags:
        - bash
        - terminal

    ## apps ##
    - role: neovim
      tags:
        - neovim
        - nvim
        - editor
        - terminal

    - role: kitty
      tags:
        - kitty
        - terminal

    ## apps ##
    - role: flatpak
      tags:
        - flatpak
        - apps

