---
# debian 12 bookworm

- name: brokenpos
  hosts: localhost
  connection: local
  vars:
    configure:
      - nano
      - kitty

    flatpak_apps:
      - com.brave.Browser
      - com.stremio.Stremio

  pre_tasks:
    - name: Check if running on correct machine
      ansible.builtin.pause:
        prompt: 'This machine does not appear to be {{ ansible_play_name }}, if you want to continue type "yes" and press enter'
      when: ansible_nodename | lower != ansible_play_name or ansible_env.container is defined
      tags: always
      register: answer
      failed_when: answer.user_input | lower != 'yes'

    - name: Load defaults
      ansible.builtin.include_vars:
        file: '{{ playbook_dir }}/../default.yml'
      tags: always

  roles:
    - role: linux
      tags: [linux, distro]

    - role: nerd-fonts
      tags: [nerd-fonts]

    - role: kde-plasma
      tags: [kde-plasma, kde, desktop]

    - role: tweaks
      tags: [distro, tweaks, fixes]

    - role: dotfiles
      tags: [dotfiles]

    - role: flatpak
      tags: [flatpak, apps]

