---
# debian 12 bookworm

- name: brokenpos
  hosts: localhost
  connection: local
  vars:
    flatpak_install:
      - com.stremio.Stremio
      - io.gitlab.librewolf-community

  roles:
    - role: extras

    - role: distro
      tags: [linux, distro]

    - role: flatpak
      tags: [flatpak, apps]

  tasks:
    - import_role:
        name: tweaks
        tasks_from: systemd-timeout.yml
      tags: tweaks

    - import_role:
        name: tweaks
        tasks_from: bluetooth-hfp.yml
      tags: tweaks

    - name: Set vm cache pressure to increase perceived speed
      ansible.builtin.copy:
        content: |
          vm.vfs_cache_pressure=40

        dest: /etc/sysctl.d/99-vfs-cache-pressure.conf
        mode: 0644
        owner: root
      become: yes
      tags: root
      when: run_root_tasks is defined and run_root_tasks

