---
# debian 12 bookworm

- name: brokenpos
  hosts: all
  gather_facts: true
  pre_tasks:
    - name: Check if running on correct machine
      ansible.builtin.pause:
        prompt: 'This machine does not appear to be {{ ansible_play_name }}, if you want to continue type "yes" and press enter'
      when: ansible_nodename | lower != ansible_play_name or ansible_env.container is defined
      tags: always
      register: answer
      failed_when: answer.user_input | lower != 'yes'

    - name: Ensure ~/.config directory exists
      ansible.builtin.file:
        path: '{{ ansible_env.HOME }}/.config'
        state: directory
      tags: always

    - name: Load defaults
      ansible.builtin.include_vars:
        file: '{{ playbook_dir }}/../vars/default.yml'
      tags: always

    - name: Load vars
      ansible.builtin.include_vars:
        file: '{{ playbook_dir }}/../vars/{{ ansible_play_name }}.yml'
      tags: always
  roles:
    ## system ##
    - role: debian
      tags:
        - debian
        - distro

    - role: kde-plasma
      tags:
        - kde-plasma
        - kde
        - desktop

    - role: fixes
      tags:
        - distro
        - fixes

    ## apps ##
    - role: flatpak
      tags:
        - flatpak
        - apps

