---
# debian 12 bookworm

- name: brokenpos
  hosts: localhost
  connection: local
  vars:
    flatpak_install:
      - com.brave.Browser
      - com.stremio.Stremio

  pre_tasks:
    - name: _Check if running on correct machine
      ansible.builtin.pause:
        prompt: 'This machine does not appear to be {{ ansible_play_name }}, if you want to continue type "yes" and press enter'
      when: ansible_nodename | lower != ansible_play_name or ansible_env.container is defined
      register: answer
      failed_when: answer.user_input | lower != 'yes'
      tags: always

    - name: _Test if password is given
      ansible.builtin.command:
        cmd: whoami
      become: yes
      register: output
      ignore_errors: yes
      changed_when: false
      tags: always

    - name: _Enable root tasks
      ansible.builtin.set_fact:
        run_root_tasks: '{{ output.rc == 0 }}'
      tags: always

    - name: _Ensure ~/.config directory exists
      ansible.builtin.file:
        path: '{{ ansible_env.HOME }}/.config'
        state: directory
      tags: always

    - name: _Load defaults
      ansible.builtin.include_vars:
        file: '{{ playbook_dir }}/../default.yml'
      tags: always
  roles:
    - role: distro
      tags: [linux, distro]

    - role: flatpak
      tags: [flatpak, apps]

  tasks:
    - import_role:
        name: tweaks
        tasks_from: systemd-timeout.yml
      tags: tweaks

    - import_role:
        name: tweaks
        tasks_from: bluetooth-hfp.yml
      tags: tweaks

    - name: Set vm cache pressure to increase perceived speed
      ansible.builtin.copy:
        content: |
          vm.vfs_cache_pressure=40

        dest: /etc/sysctl.d/99-vfs-cache-pressure.conf
        mode: 0644
        owner: root
      tags: root
      when: run_root_tasks is defined and run_root_tasks

