---
# debian 12 bookworm

- name: thorium
  hosts: localhost
  connection: local
  vars:
    kde_mouse_settings:
      - name: 'E-Signal USB Gaming Mouse'
        pid: '1241'
        vid: '41119'
        accel: ' -0.200'
        accelProfile: 1

      - name: 'Logitech Wireless Mouse PID:4022'
        pid: '1133'
        vid: '16418'
        accel: '0.200'
        accelProfile: 1

    kde_wacom_settings:
      - name: 'Wacom One by Wacom S Pen'
        pid: '1386'
        vid: '890'
        leftHanded: false
        outputArea: '0,0,1,1'

    ## other ##
    configure:
      - bin
      - profile
      - shell

      - bash
      - zsh
      - git
      - ssh
      - neovim
      - nano
      - glow
      - yt-dlp
      - zellij
      - qalculate
      - kitty

    install:
      - neovim

    flatpak_install:
      - com.brave.Browser
      - md.obsidian.Obsidian
      - io.github.Qalculate.qalculate-qt
      - com.stremio.Stremio
      - com.github.tchx84.Flatseal
      - com.usebottles.bottles
      - com.github.wwmm.easyeffects
      - org.kde.filelight
      - org.mozilla.Thunderbird
      - org.kde.krita
      - org.freecadweb.FreeCAD
      - org.qbittorrent.qBittorrent

  pre_tasks:
    - name: Check if running on correct machine
      ansible.builtin.pause:
        prompt: 'This machine does not appear to be {{ ansible_play_name }}, if you want to continue type "yes" and press enter'
      when: ansible_nodename | lower != ansible_play_name or ansible_env.container is defined
      tags: always
      register: answer
      failed_when: answer.user_input | lower != 'yes'

    - name: Test if password is given
      ansible.builtin.command:
        cmd: whoami
      become: yes
      register: output
      ignore_errors: yes

    - name: Enable root tasks
      ansible.builtin.set_fact:
        run_root_tasks: '{{ output.rc == 0 }}'

    - name: Ensure ~/.config directory exists
      ansible.builtin.file:
        path: '{{ ansible_env.HOME }}/.config'
        state: directory
      tags: always

    - name: Load defaults
      ansible.builtin.include_vars:
        file: '{{ playbook_dir }}/../default.yml'
      tags: always
  roles:
    - role: distro
      tags: [linux, distro]

    - role: nerd-fonts
      tags: [nerd-fonts]

    - role: kde-plasma
      tags: [kde-plasma, kde, desktop]

    - role: dotfiles
      tags: [dotfiles]

    - role: flatpak
      tags: [flatpak, apps]

  tasks:
    - name: Ensure ~/.config/containers exists
      ansible.builtin.file:
        path: '{{ ansible_env.HOME }}/.config/containers'
        state: directory

    # The SSD is small so i store podman images on the HDD
    - name: Set podman image storage path
      ansible.builtin.copy:
        content: |
          [storage]
          driver = "overlay"
          graphroot = "/media/slowmf/Podman"

        dest: '{{ ansible_env.HOME }}/.config/containers/storage.conf'

