---
# fedora kde 40

- name: thorium
  hosts: localhost
  connection: local
  vars:
    kde_mouse_settings:
      - name: 'E-Signal USB Gaming Mouse'
        pid: '1241'
        vid: '41119'
        accel: '0.020'
        accelProfile: 1

      - name: 'Logitech Wireless Mouse PID:4022'
        pid: '1133'
        vid: '16418'
        accel: '0.020'
        accelProfile: 1

    ## other ##
    configure:
      - bin
      - profile
      - shell

      - bash
      - zsh
      - git
      - ssh
      - neovim
      - nano
      - zellij
      - qalculate
      - kitty

    flatpak_install:
      - page.codeberg.JakobDev.jdDesktopEntryEdit
      - com.brave.Browser
      - md.obsidian.Obsidian
      - io.github.Qalculate.qalculate-qt
      - com.stremio.Stremio
      - com.github.tchx84.Flatseal
      - com.usebottles.bottles
      - com.github.wwmm.easyeffects
      - org.kde.filelight
      - org.kde.krita
      - org.freecadweb.FreeCAD
      - org.qbittorrent.qBittorrent

  pre_tasks:
    - name: _Check if running on correct machine
      ansible.builtin.pause:
        prompt: 'This machine does not appear to be {{ ansible_play_name }}, if you want to continue type "yes" and press enter'
      when: ansible_nodename | lower != ansible_play_name or ansible_env.container is defined
      register: answer
      failed_when: answer.user_input | lower != 'yes'
      tags: always

    - name: _Check if running on correct distro
      ansible.builtin.pause:
        prompt: 'This machine does not appear to be running Fedora 40, if you want to continue type "yes" and press enter'
      when: ansible_distribution != "Fedora" or ansible_distribution_major_version != "40"
      register: answer
      failed_when: answer.user_input | lower != 'yes'
      tags: always

    - name: _Test if password is given
      ansible.builtin.command:
        cmd: whoami
      become: yes
      register: output
      ignore_errors: yes
      changed_when: false
      tags: always

    - name: _Enable root tasks
      ansible.builtin.set_fact:
        run_root_tasks: '{{ output.rc == 0 }}'
      tags: always

    - name: _Ensure ~/.config directory exists
      ansible.builtin.file:
        path: '{{ ansible_env.HOME }}/.config'
        state: directory
      tags: always

    - name: _Load defaults
      ansible.builtin.include_vars:
        file: '{{ playbook_dir }}/../default.yml'
      tags: always
  roles:
    - role: distro
      tags: [linux, distro]

    - role: nerd-fonts
      tags: [nerd-fonts]

# this is dangerous as plasma 6.0 may be quite a bit different
#    - role: kde-plasma
#      tags: [kde-plasma, kde, desktop]

    - role: dotfiles
      tags: [dotfiles]

    - role: flatpak
      tags: [flatpak, apps]

  tasks:
    # TODO redo tweaks so it works like dotfiles and run tweaks from an array
    - import_role:
        name: tweaks
        tasks_from: systemd-timeout.yml
      tags: tweaks

    - import_role:
        name: tweaks
        tasks_from: bluetooth-hfp.yml
      tags: tweaks

#    - name: Ensure ~/.config/containers exists
#      ansible.builtin.file:
#        path: '{{ ansible_env.HOME }}/.config/containers'
#        state: directory

# as i installed fedora on the big SSD now i do not need this
    # The SSD is small so i store podman images on the HDD
#    - name: Set podman image storage path
#      ansible.builtin.copy:
#        content: |
#          [storage]
#          driver = "overlay"
#          graphroot = "/media/slowmf/Podman"
#
#        dest: '{{ ansible_env.HOME }}/.config/containers/storage.conf'

