---
- block:
    - name: Ensure ~/.local/bin exists
      ansible.builtin.file:
        path: '{{ ansible_env.HOME }}/.local/bin'
        state: directory

    # TODO maybe switch to the archived one as appimage requires libfuse
    - name: Download neovim
      vars:
        neovim_release: 'v0.9.5'
        neovim_checksum: '0c82e5702af7a11fbb916a11b4a82e98928abf8266c74b2030ea740340437bf9'
      ansible.builtin.get_url:
        url: 'https://github.com/neovim/neovim/releases/download/{{ neovim_release }}/nvim.appimage'
        checksum: 'sha256:{{ neovim_checksum }}'
        dest: '{{ ansible_env.HOME }}/.local/bin/nvim'
        mode: u+rwx # make sure its executable
  when: neovim_install and not neovim_flatpak

- name: Link neovim configuration directory (native)
  ansible.builtin.file:
    src: '{{ role_path }}/nvim'
    dest: '{{ ansible_env.HOME }}/.config/nvim'
    state: link
  when: not neovim_flatpak

- name: Link neovim configuration directory (flatpak)
  ansible.builtin.file:
    src: '{{ role_path }}/nvim'
    dest: '{{ ansible_env.HOME }}/.var/app/io.neovim.nvim/config/nvim'
    state: link
  when: neovim_flatpak

