---
# installs proton-ge for steam, use 'release' variable to set version

- name: Ensure steam proton directory exists
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.steam/root/compatibilitytools.d'
    state: directory

- name: Check if proton-ge {{ release }} already installed
  stat:
    path: '{{ ansible_env.HOME }}/.steam/root/compatibilitytools.d/{{ release }}/'
  register: installed

- name: Download proton-ge {{ release }}
  ansible.builtin.get_url:
    url: 'https://github.com/GloriousEggroll/proton-ge-custom/releases/download/{{ release }}/{{ release }}.tar.gz'
    checksum: 'sha512:https://github.com/GloriousEggroll/proton-ge-custom/releases/download/{{ release }}/{{ release }}.sha512sum'
    dest: '{{ ansible_env.HOME }}/.steam/root/compatibilitytools.d/{{ release }}.tar.gz'
  when: not installed.stat.exists

- name: Install proton-ge {{ release }}
  ansible.builtin.unarchive:
    src: '{{ ansible_env.HOME }}/.steam/root/compatibilitytools.d/{{ release }}.tar.gz'
    dest: '{{ ansible_env.HOME }}/.steam/root/compatibilitytools.d/'
    remote_src: true
  when: not installed.stat.exists

- name: Delete proton-ge {{ release }} archive
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.steam/root/compatibilitytools.d/{{ release }}.tar.gz'
    state: absent

