on:
  schedule:
    # run at 8 AM UTC every sunday
    - cron: '0 8 * * 0'

  push:
    branches:
      - 'master'
    paths:
      - 'boxes/**'
      - '.github/workflows/containers.yml'

jobs:
  build_containers:
    # i am using 24.04 cause 22.04 has too old version of podman
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: read
    defaults:
      run:
        # justfile is here
        working-directory: boxes
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2

      - name: Install podman and buildah
        run: |
          sudo apt-get update
          sudo apt-get -y install podman buildah

      - name: Build and Publish
        run: |
          echo "${TOKEN:?}" | podman login \
            --username "${{ github.actor }}" \
            --password-stdin \
            "ghcr.io"

          just publish-all

          podman logout --all
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
