on:
  schedule:
    # run at 8 AM UTC every sunday
    - cron: '0 8 * * 0'

  push:
    branches:
      - 'master'
    paths:
      - 'boxes/**'
      - '.github/workflows/containers.yml'

jobs:
  build_containers:
    strategy:
      matrix:
        # names of container images go here!
        image_name:
          - dev-fedora
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    defaults:
      run:
        # justfile is here
        working-directory: boxes
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2

      # idk if it works properly with docker
      - name: Installing podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman

      - name: Login for the registry
        run: just login-ci
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish the image
        run: just publish "${{ matrix.image_name }}"

      - name: Logout of the registry
        run: just logout-ci
