on:
  schedule:
    # run at 8 AM UTC every sunday
    - cron: '0 8 * * 0'

  push:
    branches:
      - 'master'
    paths:
      - 'boxes/**'
      - '.github/workflows/containers.yml'

jobs:
  build_containers:
    strategy:
      matrix:
        # names of container images go here!
        image_name:
          - dev-fedora
    # i am using 24.04 cause 22.04 has too old version of podman
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: read
    defaults:
      run:
        # justfile is here
        working-directory: boxes
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2

      # idk if it works properly with docker
      - name: Install podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman

      - name: Build and Publish
        run: |
          just login-ci
          just publish "{{ matrix.image_name }}"
          just logout-ci
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
